# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20160204_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_ordered', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
        ),
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=b'Date Ordered')),
                ('items_ordered', models.ManyToManyField(through='inventory.ItemOrder', to='inventory.Item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='itemorder',
            name='stock_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StockOrder'),
        ),
    ]
