# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockorder_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockorder',
            name='delivery_date',
            field=models.DateField(default=datetime.date.today, verbose_name=b'Delivery Date'),
        ),
        migrations.AlterField(
            model_name='stockorder',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name=b'Date Ordered'),
        ),
    ]
