# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20160224_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.date.today, verbose_name=b'Date Ordered')),
                ('completion_date', models.DateField(default=datetime.date.today, verbose_name=b'Completion Date')),
                ('completed', models.BooleanField(default=False, verbose_name=b'Completed?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
            ],
        ),
    ]
