# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_productorder_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='customer',
        ),
    ]
