# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20160224_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='req_item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supply',
        ),
        migrations.RemoveField(
            model_name='product',
            name='to_make',
        ),
    ]
