# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20160224_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='req_item',
            field=models.ManyToManyField(through='inventory.ItemRequirement', to='inventory.Item'),
        ),
    ]
