# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_product_req_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_changed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StockCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=b'Date Ordered')),
                ('reason', models.CharField(max_length=256)),
                ('items_changed', models.ManyToManyField(through='inventory.StockChange', to='inventory.Item')),
            ],
        ),
        migrations.AlterField(
            model_name='stockorder',
            name='date',
            field=models.DateTimeField(verbose_name=b'Date Ordered'),
        ),
        migrations.AlterField(
            model_name='stockorder',
            name='delivery_date',
            field=models.DateField(verbose_name=b'Delivery Date'),
        ),
        migrations.AddField(
            model_name='stockchange',
            name='correction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.StockCorrection'),
        ),
        migrations.AddField(
            model_name='stockchange',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
    ]
