# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_stockcorrection_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='minimum',
            field=models.IntegerField(default=5),
        ),
    ]
