# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_item_minimum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='minimum',
            field=models.IntegerField(default=5, verbose_name=b'Minimum stock warning'),
        ),
    ]
