# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20160301_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product specifications'},
        ),
        migrations.AlterField(
            model_name='itemrequirement',
            name='number_required',
            field=models.IntegerField(default=1),
        ),
    ]
