# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='number_ordered',
            field=models.IntegerField(default=1),
        ),
    ]
