# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_productorder_number_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockcorrection',
            old_name='items_changed',
            new_name='items_adjusted',
        ),
    ]
