# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_stockcorrection_adjusted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=b'Date Ordered')),
                ('completion_date', models.DateField(verbose_name=b'Completion Date')),
                ('completed', models.BooleanField(default=False, verbose_name=b'Completed?')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_ordered', models.IntegerField(default=0)),
                ('completion_date', models.DateField(verbose_name=b'Completion Date')),
                ('completed', models.BooleanField(default=False, verbose_name=b'Completed?')),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.CustomerOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
            ],
        ),
        migrations.AddField(
            model_name='customerorder',
            name='product',
            field=models.ManyToManyField(through='inventory.ProductRequirement', to='inventory.Product'),
        ),
    ]
