# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20160316_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_ordered', models.IntegerField(default=0)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.CustomerOrder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
        ),
        migrations.AddField(
            model_name='customerorder',
            name='additional_items',
            field=models.ManyToManyField(through='inventory.AdditionalItem', to='inventory.Item'),
        ),
    ]
