# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20160316_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalitem',
            name='added',
            field=models.BooleanField(default=False, verbose_name=b'Added to order?'),
        ),
    ]
