# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20160316_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembler',
            name='website',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
