# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_auto_20160316_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorder',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemorder',
            name='stock_order',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockchange',
            name='correction',
        ),
        migrations.RemoveField(
            model_name='stockchange',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stockcorrection',
            name='items_adjusted',
        ),
        migrations.RemoveField(
            model_name='stockorder',
            name='items_ordered',
        ),
        migrations.RemoveField(
            model_name='stockorder',
            name='supplier',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='assemblyorder',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='completed',
        ),
        migrations.DeleteModel(
            name='ItemOrder',
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
        migrations.DeleteModel(
            name='StockChange',
        ),
        migrations.DeleteModel(
            name='StockCorrection',
        ),
        migrations.DeleteModel(
            name='StockOrder',
        ),
    ]
