# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_auto_20160406_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='tracking',
            field=models.URLField(blank=True, max_length=100, verbose_name=b'Tracking:'),
        ),
    ]
